# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install deps
      run: poetry install --no-root
    - name: Cache build venv
      id: cached-poetry-dependecies
      uses: actions/cache@v3
      with:
        path: /home/runner/work//home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Recover build venv
      id: cached-poetry-dependecies
      uses: actions/cache@v3
      with:
        path: /home/runner/work//home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Lint
      run : |
        poetry run test lint
  formatter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Recover build venv
      id: cached-poetry-dependecies
      uses: actions/cache@v3
      with:
        path: /home/runner/work//home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Formatter
      run: |
        poetry run test formatter     
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Recover build venv
      id: cached-poetry-dependecies
      uses: actions/cache@v3
      with:
        path: /home/runner/work//home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venvv
    - name: Test
      run : |
        poetry run test test
          build:
  sec_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Recover build venv
      id: cached-poetry-dependecies
      uses: actions/cache@v3
      with:
        path: /home/runner/work//home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv
    - name: Sec Test
      run : |
        poetry run test security
        
        build:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Recover build venv
      id: cached-poetry-dependecies
      uses: actions/cache@v3
      with:
        path: /home/runner/work//home/runner/work/iac-labs/iac-labs/example-app/.venv
        key: ${{ runner.os }}-venv  
    - name: Test with pytest
      run: |
        poetry run test pytest
